/*
Copyright 2026 dapperdivers.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package knight

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"strings"

	appsv1 "k8s.io/api/apps/v1"
	aiv1alpha1 "github.com/dapperdivers/roundtable/api/v1alpha1"
)

// GenerateFlakeNix produces the flake.nix content for Nix package provisioning.
func GenerateFlakeNix(knight *aiv1alpha1.Knight) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by roundtable-operator\n")
	sb.WriteString("# Knight: " + knight.Name + "\n")
	sb.WriteString("{\n")
	sb.WriteString("  inputs.nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";\n")
	sb.WriteString("  outputs = { self, nixpkgs }:\n")
	sb.WriteString("    let\n")
	sb.WriteString("      system = \"x86_64-linux\";\n")
	sb.WriteString("      pkgs = nixpkgs.legacyPackages.${system};\n")
	sb.WriteString("    in {\n")
	sb.WriteString("      packages.${system}.default = pkgs.buildEnv {\n")
	sb.WriteString("        name = \"knight-" + knight.Name + "-tools\";\n")
	sb.WriteString("        paths = with pkgs; [\n")
	for _, pkg := range knight.Spec.Tools.Nix {
		sb.WriteString("          " + pkg + "\n")
	}
	sb.WriteString("        ];\n")
	sb.WriteString("      };\n")
	sb.WriteString("    };\n")
	sb.WriteString("}\n")
	return sb.String()
}

// GenerateMiseToml produces the mise configuration for tool provisioning.
func GenerateMiseToml(knight *aiv1alpha1.Knight) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by roundtable-operator\n")
	sb.WriteString("# Knight: " + knight.Name + "\n")
	sb.WriteString("# Domain: " + knight.Spec.Domain + "\n\n")

	if knight.Spec.Tools != nil && len(knight.Spec.Tools.Mise) > 0 {
		sb.WriteString("[tools]\n")
		for _, tool := range knight.Spec.Tools.Mise {
			sb.WriteString(fmt.Sprintf("%s = \"latest\"\n", tool))
		}
	}

	return sb.String()
}

// DeploymentSpecHash computes a hash of the deployment spec for drift detection.
func DeploymentSpecHash(deploy *appsv1.Deployment) string {
	// Hash the pod template spec to detect meaningful changes
	// (ignore replicas, status, metadata timestamps)
	data, _ := json.Marshal(deploy.Spec.Template.Spec)
	hash := sha256.Sum256(data)
	return fmt.Sprintf("%x", hash[:8])
}
