# TODO: Redis/Valkey HelmRelease for shared knight state
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: roundtable
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: "19.*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    architecture: standalone
    auth:
      enabled: true
      existingSecret: redis-secret
    master:
      persistence:
        size: 1Gi
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          memory: 256Mi
