apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: roundtable
spec:
  interval: 30m
  chart:
    spec:
      chart: nats
      version: "1.2.*"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  values:
    config:
      jetstream:
        enabled: true
        memoryStore:
          maxSize: 256Mi
        fileStore:
          maxSize: 1Gi
          storageDirectory: /data/jetstream
    container:
      merge:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi
    natsBox:
      enabled: true
    persistence:
      enabled: true
      size: 2Gi
